@extends('layouts.app')
@section('title', 'Админка')

@section('menu')
    @include('menu.admin_menu')
    
@endsection

@section('content')
    <p class="text-justify">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Facilis culpa voluptate repellendus, veritatis aliquam corrupti accusantium beatae aperiam ut, id temporibus, voluptatibus autem. Magnam laborum consequatur, quod exercitationem sequi perferendis expedita itaque doloremque, culpa vel sit rem illo necessitatibus minus dignissimos voluptatem facere recusandae voluptate cumque. Officia, voluptatum delectus ab incidunt eveniet pariatur amet. Rerum ipsa voluptatibus vel facere mollitia quas atque ducimus minima alias nam numquam molestiae ab temporibus aspernatur voluptate voluptates suscipit eius ratione velit, praesentium ipsum neque qui, obcaecati doloribus! Esse itaque, quaerat modi perferendis tempora quisquam et? Ipsa corporis repellat neque. Nihil nostrum provident corporis quidem quisquam beatae nisi voluptatum. Temporibus aspernatur odio eos culpa hic quod minima id deserunt reiciendis quos minus delectus architecto adipisci dignissimos iste qui ratione, suscipit quidem molestias amet praesentium, molestiae natus explicabo excepturi. Temporibus porro repudiandae optio iusto architecto expedita quae dignissimos molestiae nam, inventore voluptates ipsa quo corporis magni numquam mollitia aliquid veritatis a beatae deleniti voluptate est! Natus, est, earum fugiat, ab minus dicta temporibus officia voluptatibus optio reprehenderit ducimus beatae. Reiciendis provident dolorem id exercitationem neque ea quam repellendus sit nulla quod voluptas, officiis harum ab est recusandae, iusto saepe laborum maiores. Nulla modi perferendis expedita, omnis ex, quae quo dolores unde fuga eius rem in similique aliquid dolorum provident placeat vero laudantium quia dolore aperiam ad illo. Fuga quibusdam modi exercitationem beatae at soluta quasi, quas sed totam aspernatur velit sunt, reiciendis, quis ut labore! Provident nostrum rem tenetur excepturi sunt voluptas, ab voluptatem eligendi. Ipsam odio asperiores necessitatibus aliquid magni nobis! Labore totam, dicta cum perferendis, odit nulla necessitatibus error at inventore quo commodi esse eligendi accusamus quibusdam, velit nostrum sunt porro temporibus tempora suscipit? Tenetur officiis dolore architecto quibusdam magnam voluptatum ratione itaque in pariatur, quo rerum? Voluptatem sunt impedit ipsam aut, possimus nobis?</p>
@endsection
